### ISSUE TITLE
Fix 3 finger triple tap bug on iOS 13

### ISSUE THREAD

**Issue by brendanlensink** [steamclock/switchcraft#17]
It looks like 3x3 tap is broken on current iOS 13 betas, but 2x3 still works. We should switch the default if it looks like this isn't going to be fixed soon.

**Comment by apike** [comment]
I would suspect we can still support 3x3, probably just an API tweak?

**Comment by brendanlensink** [comment]
I suspect this has something to do with Apple adding triple tap to undo/copy/paste since changing the gesture to two finger triple tap fixed it in Flock.

**Comment by brendanlensink** [comment]
The plot thickens, updating my device to 13.1 beta 2 fixed this issue.

The next steps depend on what versions are affected, and if the 13.0 public release will have this bug or not.

Assuming it does, we should change the default to 2x3 tap.

**Comment by brendanlensink** [comment]
Seems like this was just an iOS beta bug that isn't happening anymore.
