### ISSUE TITLE
Display build number in the environment switcher

### ISSUE THREAD

**Issue by abey** [steamclock/switchcraft#5]

**Comment by brendanlensink** [comment]
What’s the motivation for this?

**Comment by abey** [comment]
@brendanlensink https://app.zenhub.com/workspace/o/steamclock/wealthbar/issues/506

**Comment by brendanlensink** [comment]
I can’t see that repo

**Comment by apike** [comment]
Basically that often if you can't log in, you can't tell what build you have.
